name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build app
      run: xcodebuild clean build test -enableCodeCoverage YES -project CountryPicker/CountryPicker.xcodeproj -scheme CountryPicker -destination 'platform=iOS Simulator,name=iPhone 8' ONLY_ACTIVE_ARCH=YES
    - name: Run tests
      run: xcodebuild -project 'CountryPicker/CountryPicker.xcodeproj' -scheme 'CountryPicker' -destination 'platform=iOS Simulator,name=iPhone 8' test | xcpretty

